services:
  - type: web
    name: asme-web
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements-render.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: ASME_SECRET_KEY
        generateValue: true
